# Generated by Django 2.0.1 on 2018-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_passed', models.CharField(max_length=20)),
                ('year_of_passing', models.CharField(max_length=20)),
                ('degree_name', models.CharField(max_length=20)),
                ('discipline', models.TextField(max_length=50)),
                ('board', models.CharField(max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('division', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Research_Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_journals', models.IntegerField()),
                ('no_of_papers_sci_journal', models.IntegerField()),
                ('no_of_papers_scopus_journal', models.IntegerField()),
                ('no_of_conference_papers', models.IntegerField()),
                ('no_of_books_published', models.IntegerField()),
                ('no_of_short_courses', models.IntegerField()),
                ('no_of_seminars', models.IntegerField()),
                ('no_of_professional_training_received', models.IntegerField()),
                ('no_of_sponsored_research_project', models.IntegerField()),
            ],
        ),
    ]
