# Generated by Django 2.0.1 on 2018-01-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_qualification_research_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='areas_of_specialization',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='personal',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
