# Generated by Django 2.0.1 on 2018-01-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20180127_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='board',
            new_name='board_or_university_or_institution',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='cgpa',
            new_name='cgpa_or_marks',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='division',
            new_name='class_or_division',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='discipline',
            new_name='discipline_or_subjects',
        ),
    ]
