# Generated by Django 2.0.1 on 2018-01-31 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_qualification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
