# Generated by Django 2.0.1 on 2018-01-31 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20180131_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='user',
            new_name='username1',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='user',
            new_name='username1',
        ),
    ]
