# Generated by Django 2.0.1 on 2018-01-31 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20180131_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='username1',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='username1',
            new_name='user',
        ),
    ]
