# Generated by Django 2.0.1 on 2018-02-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20180131_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_publications',
            name='first_corresponding_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research_publications',
            name='impact_factor',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='research_publications',
            name='no_of_authors',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='research_publications',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='research_publications',
            name='single_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research_publications',
            name='three_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research_publications',
            name='two_author',
            field=models.BooleanField(default=False),
        ),
    ]
