# Generated by Django 2.0.1 on 2018-02-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_auto_20180225_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Research_Publications',
        ),
    ]
