# Generated by Django 2.0.1 on 2018-04-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_auto_20180401_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_publications',
            name='user',
        ),
        migrations.DeleteModel(
            name='Research_Publications',
        ),
    ]
