# Generated by Django 2.0.1 on 2018-04-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0019_research_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_publications',
            name='impact_factor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
