# Generated by Django 2.0.1 on 2018-04-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0023_research_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_publications',
            name='user',
        ),
        migrations.DeleteModel(
            name='Research_Publications',
        ),
    ]
